name: android_usb_printer
description: android_usb_printer
version: 0.0.2+3
author: lixiaohong<liyufengisme@gmail.com>
homepage: https://github.com/liyufengrex/android_usb_printer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rex.android_usb_printer
        pluginClass: AndroidUsbPrinterPlugin
